# Generated by Django 4.0.1 on 2022-02-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_is_verified_profile_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nudgedata',
            field=models.JSONField(null=True),
        ),
    ]
