# Generated by Django 4.0.1 on 2022-02-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycandle', '0002_upl'),
    ]

    operations = [
        migrations.CreateModel(
            name='INDUSINDBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='SUNPHARMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TATACONSUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
    ]
