# Generated by Django 4.0.1 on 2022-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycandle', '0003_indusindbk_sunpharma_tataconsum'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHARTIARTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='BPCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='BRITANNIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='COALINDIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='GRASIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='INFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ITC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='JSWSTEEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ONGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TATAMOTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TITAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='WIPRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
    ]
