# Generated by Django 4.0.1 on 2022-02-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycandle', '0005_adaniports_asianpaint_bajfinance_cipla_divislab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AXISBANK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='BAJAJFINSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='DRREDDY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='EICHERMOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HDFCBANK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HDFCLIFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HEROMOTOCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HINDUNILVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ICICIBANK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='LT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='MARUTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='NESTLEIND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='POWERGRID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='RELIANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='SBILIFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='SBIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TATASTEEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TECHM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ULTRACEMCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance', models.CharField(blank=True, max_length=300)),
                ('Monday', models.CharField(blank=True, max_length=1500)),
                ('Tuesday', models.CharField(blank=True, max_length=1500)),
                ('Wednesday', models.CharField(blank=True, max_length=1500)),
                ('Thursday', models.CharField(blank=True, max_length=1500)),
                ('Friday', models.CharField(blank=True, max_length=1500)),
            ],
        ),
    ]
