from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(NTPC)
admin.site.register(UPL)
admin.site.register(SUNPHARMA)
admin.site.register(TATACONSUM)
admin.site.register(INDUSINDBK)
admin.site.register(ONGC)
admin.site.register(IOC)
admin.site.register(BHARTIARTL)
admin.site.register(ITC)
admin.site.register(WIPRO)
admin.site.register(TCS)
admin.site.register(BRITANNIA)
admin.site.register(COALINDIA)
admin.site.register(GRASIM)
admin.site.register(TATAMOTORS)
admin.site.register(TITAN)
admin.site.register(BPCL)
admin.site.register(JSWSTEEL)
admin.site.register(INFY)
admin.site.register(HDFC)
admin.site.register(DIVISLAB)
admin.site.register(SHREECEM)
admin.site.register(CIPLA)
admin.site.register(ADANIPORTS)
admin.site.register(HCLTECH)
admin.site.register(HINDALCO)
admin.site.register(BAJFINANCE)
admin.site.register(KOTAKBANK)
admin.site.register(ASIANPAINT)
admin.site.register(NESTLEIND)
admin.site.register(HDFCLIFE)
admin.site.register(ULTRACEMCO)
admin.site.register(RELIANCE)
admin.site.register(TATASTEEL)
admin.site.register(HINDUNILVR)
admin.site.register(SBILIFE)
admin.site.register(LT)
admin.site.register(DRREDDY)
admin.site.register(HDFCBANK)
admin.site.register(EICHERMOT)
admin.site.register(SBIN)
admin.site.register(BAJAJFINSV)
admin.site.register(AXISBANK)
admin.site.register(HEROMOTOCO)
admin.site.register(ICICIBANK)
admin.site.register(POWERGRID)
admin.site.register(TECHM)
admin.site.register(MARUTI)
admin.site.register(MM)

